### ISSUE TITLE
Module does not work with version 1.14.1

### ISSUE THREAD

**Issue by buzzzo** [smart4life/humhub-auth-basic#5]
As of humhub version 1.14.1 auth-basic module does not work anymore.

Is it possible to have an update ?

Thx

**Comment by sebmennetrier** [comment]
Hi @buzzzo,

I will take a look ASAP.

**Comment by buzzzo** [comment]
FYI: this is the error in app.log:

2023-05-18 14:44:52 [172.18.2.51][-][ti8bblvnbragdughmu5pjn9ljk][error][Error] Error: Call to undefined method humhub\modules\user\authclient\AuthClientHelpers::getUserByAuthClient() in /var/vhost/hub.gci.it/protected/modules/auth-basic/Events.php:28

Seems that function/method AuthClientHelpers::getUserByAuthClient() is not present anymore

**Comment by ArchBlood** [comment]
Use [`/protected/humhub/modules/user/services/AuthClientUserService.php`](https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/services/AuthClientUserService.php) now

**Comment by sebmennetrier** [comment]
It should be fixed. Please let me know if it doesn't work for you.
Thanks for your report and your help.

**Comment by buzzzo** [comment]
> It should be fixed. Please let me know if it doesn't work for you. Thanks for your report and your help.

Thx , i will test it asap

**Comment by buzzzo** [comment]
Does not work.
Seems that you have simply renamed the class to import but not verified if the function exists in it.
Infact the error remain the same:

2023-05-31 16:53:23 [172.18.2.51][-][cvhcq1jsse2g90tu75v7h5k4cm][error][Error] Error: Call to undefined method humhub\modules\user\authclient\AuthClientHelpers::getUserByAuthClient() in /var/vhost/hub.gci.it/protected/modules/auth-basic/Events.php:39

And in protected/humhub/modules/user/authclient/AuthClientHelpers.php the function getUserByAuthClient does not exists

**Comment by buzzzo** [comment]
> Use [`/protected/humhub/modules/user/services/AuthClientUserService.php`](https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/services/AuthClientUserService.php) now

getUserByAuthClient  seems to be non available in this class.
So which method should be used to replace it in the code ?

**Comment by sebmennetrier** [comment]
@buzzzo, I'm sorry but I don't understand your error. I didn't only renamed the class to import.

I added [a check to see if the new class "AuthClientService" exists](https://github.com/smart4life/humhub-auth-basic/pull/6/files#diff-666c020a6d1e6a59ba261ba9316aaa19e27dbd851bcc4fdcaecaa278ddc96c10R29) and if exists, it is used otherwise, the old class is used. So I don't understand your comment and your error.

The method humhub\modules\user\authclient\AuthClientHelpers::getUserByAuthClient() sould not be called if you have the last version (0.2.0) of auth-basic and a version of humhub >= 1.14 that contains the class ["humhub\modules\user\services\AuthClientService"](https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/services/AuthClientService.php).

**Comment by ArchBlood** [comment]
> @buzzzo, I'm sorry but I don't understand your error. I didn't only renamed the class to import.
> 
> I added [a check to see if the new class "AuthClientService" exists](https://github.com/smart4life/humhub-auth-basic/pull/6/files#diff-666c020a6d1e6a59ba261ba9316aaa19e27dbd851bcc4fdcaecaa278ddc96c10R29) and if exists, it is used otherwise, the old class is used. So I don't understand your comment and your error.
> 
> The method humhub\modules\user\authclient\AuthClientHelpers::getUserByAuthClient() sould not be called if you have the last version (0.2.0) of auth-basic and a version of humhub >= 1.14 that contains the class ["humhub\modules\user\services\AuthClientService"](https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/services/AuthClientService.php).

`AuthClientHelpers::getUserByAuthClient()` can't be called in newer versions of HumHub as the method was changed to a new method that calls method `storeAuthClientForUser()` which will always call `(new AuthClientUserService($user))->add($authClient);`

For version comparing the bottom code can be used;
```php
if (version_compare(Yii::$app->version, '1.3', '=>')) {
    // Use some 1.3+ features here
} else {
     // Compatibility code for older versions
}
```

**Comment by buzzzo** [comment]
> @buzzzo, I'm sorry but I don't understand your error. I didn't only renamed the class to import.
> 
> I added [a check to see if the new class "AuthClientService" exists](https://github.com/smart4life/humhub-auth-basic/pull/6/files#diff-666c020a6d1e6a59ba261ba9316aaa19e27dbd851bcc4fdcaecaa278ddc96c10R29) and if exists, it is used otherwise, the old class is used. So I don't understand your comment and your error.
> 
> The method humhub\modules\user\authclient\AuthClientHelpers::getUserByAuthClient() sould not be called if you have the last version (0.2.0) of auth-basic and a version of humhub >= 1.14 that contains the class ["humhub\modules\user\services\AuthClientService"](https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/services/AuthClientService.php).

Thx for reply 

For some strange reasons if  the code match the else as the class AuthClientService would not exists on my system.
But my installation is 1.14.x .

Just for test i've comment out the class_exists checks and also the else in order to execute just 
the part of code for the new code and i was able to logon .
So seems that (at least for me) the check of the new class is not validated correctly 

 #if (class_exists("AuthClientService")) {
                    $authClientService = new AuthClientService($login->authClient);
                    $user = $authClientService->getUser();
                 #if (class_exists("AuthClientService")) {
                    $authClientService = new AuthClientService($login->authClient);
                    $user = $authClientService->getUser();
                    if ($user == null) {
                        $user = $authClientService->createUser($login->authClient);
                    }
                    if ($user != null) {
                        Yii::$app->user->login($user);
                    }
                {
                #    $user = AuthClientHelpers::getUserByAuthClient($login->authClient);
                #    if ($user == null) {
                #        $user = AuthClientHelpers::createUser($login->authClient);
                #    }
                #    if ($user != null) {
                #        Yii::$app->user->login($user);
                #    }
                #}

**Comment by CodeShakingSheep** [comment]
I just installed HumHub 1.15.2 and I can confirm what @buzzzo wrote. For some reason the check
```php
if (class_exists("AuthClientService"))
```
returns false and this goes in the else block although the class is present from v 1.14 onwards. I verified it on my system. So perhaps it can be fixed with checking the HumHub version instead of `class_exists`. I applied a temporary fix. Like this it works.

```php
 if (true) {
    // Manual temp fix
    //if (class_exists("AuthClientService")) {
    $authClientService = new AuthClientService($login->authCli>
    $user = $authClientService->getUser();
    if ($user == null) {
        $user = $authClientService->createUser($login->authCli>
    }
    if ($user != null) {
        Yii::$app->user->login($user);
    }
} else {
    $user = AuthClientHelpers::getUserByAuthClient($login->aut>
    if ($user == null) {
        $user = AuthClientHelpers::createUser($login->authClie>
    }
    if ($user != null) {
        Yii::$app->user->login($user);
    }
}

```

Edit: Proposed fix by @ArchBlood is much better. Changed if condition to `version_compare(Yii::$app->version, '1.3', '=>')`.

Edit2: There was a small typo with the comparison operator. It needs to be  `version_compare(Yii::$app->version, '1.3', '>=')` instead of  `version_compare(Yii::$app->version, '1.3', '=>')`.

**Comment by sebmennetrier** [comment]
Hi @CodeShakingSheep,

I don't reproduce the issue, but I created the PR #7 that compare the version. Please, can you test it in order to know if this patch fix the issue on your side ?

**Comment by ArchBlood** [comment]
> Hi @CodeShakingSheep,
> 
> I don't reproduce the issue, but I created the PR #7 that compare the version. Please, can you test it in order to know if this patch fix the issue on your side ?

This could be a configuration in your server tests that makes it so it's not reproducible and something that should be documented for future issues that could pop up. I've also noticed that you redirect login to password recovery, is this a necessary method? If needed why is it in its own `if()`, how it's setup it automatically just redirects in a never ending loop if you visit the `user/auth/login` or click the Sign In button if guest access is allowed, this isn't the best option and should be handled in a controller instead.

**Comment by CodeShakingSheep** [comment]
@sebmennetrier @ArchBlood I just found out the reason why the original condition fails on my system. It's the same reason as here: https://stackoverflow.com/questions/14948413/why-does-the-class-exists-function-return-false

This `if (class_exists("AuthClientService")) {` returns `false`.

But this `if (class_exists("humhub\modules\user\services\AuthClientService")) {` returns `true` and works as expected. So, this would be an alternative solution to comparing HumHub version.

**Comment by ArchBlood** [comment]
> @sebmennetrier @ArchBlood I just found out the reason why the original condition fails on my system. It's the same reason as here: https://stackoverflow.com/questions/14948413/why-does-the-class-exists-function-return-false
> 
> This `if (class_exists("AuthClientService")) {` returns `false`.
> 
> But this `if (class_exists("humhub\modules\user\services\AuthClientService")) {` returns `true` and works as expected. So, this would be an alternative solution to comparing HumHub version.

To be honest `class_exists()` should be done like this `if (class_exists(AuthClientService::class)) {` in this instance, but the easier and less error prone way would be using `version_compare()` as you're wanting to check the version of HumHub used and if the class is there it's used. You can also do something like the following example as well;

### Example
```php
$requiredVersion = '1.14';
$latestVersion = HumHubAPI::getLatestHumHubVersion();

if ($latestVersion !== false) {
    if (version_compare($latestVersion, $requiredVersion, '<')) {
        echo "This script requires HumHub version $requiredVersion or higher.";
    } else {
        // Check if the class exists
        if (class_exists(\humhub\modules\user\services\AuthClientService::class)) {
            // The class exists and HumHub version requirement is met
            // You can proceed to use the class
            $object = new \humhub\modules\user\services\AuthClientService();
            // ... do something with the class object
        } else {
            echo "The required class does not exist.";
        }
    }
} else {
    echo "Failed to retrieve the latest HumHub version.";
}
```
